# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$directory$character'

# Inserts a blank line between shell prompts
add_newline = false

[line_break]
disabled = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[\$](bold darkblue)'
error_symbol =  '[\$](bold red)'

[directory]
style = "navy bold"
truncation_symbol = '…/'

[package]
disabled = true

[battery]
disabled = true

[nodejs]
disabled = true
